# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: UpdateSDK

on:
  workflow_dispatch:
  schedule:
    - cron: '4 6 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  UpdateSDK:
    uses: dorssel/workflows/.github/workflows/update-dotnet-sdk.yml@main
